name: BranchCI

env:
  CODECOV_TOKEN: "c0feeb47-4495-4495-8247-e706294cafdf"
  NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
  NEXT_PUBLIC_GRAPHQL_URL: ${{ secrets.NEXT_PUBLIC_GRAPHQL_URL }}

on:
  push:
    branches-ignore:
      - master

jobs:
  test_unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
        name: Install dependencies
      - run: yarn run test
        name: Run test
      - run: bash <(curl -s https://codecov.io/bash)
        name: Upload Coverage to Codecov

  test_e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
        name: Install dependencies
      - run: yarn run build
        name: Build production
      - run: yarn run test:e2e
        name: Run E2E Tests

  test_lint:
    name: Lint Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
        name: Install dependencies
      - run: yarn run test:lint
        name: Run test
